# Generated by Django 5.2.7 on 2025-10-21 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='affinity_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='AI 호감도 점수'),
        ),
    ]
